[package]
name = "spanish_inquisition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dateparser = "0.2.0"
pdf-extract = "0.6.5"
